# ====== Project Variants ======
# Auto-generated by Pipeline/scripts/generate_project_variants.py
# Do not manually edit generated entries. Update the CSV and regenerate instead.

from enum import Enum


class ProjectVariants(Enum):
    ALIBABA_NACOS_CVE_2021_44667 = {
        "name": "alibaba__nacos_CVE-2021-44667_2.0.3",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/ALIBABA_NACOS_CVE_2021_44667.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ALIBABA_ONE_JAVA_AGENT_CVE_2022_25842 = {
        "name": "alibaba__one-java-agent_CVE-2022-25842_0.0.1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/ALIBABA_ONE_JAVA_AGENT_CVE_2022_25842.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_ACTIVEMQ_CVE_2014_3576 = {
        "name": "apache__activemq_CVE-2014-3576_5.10.2",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_ACTIVEMQ_CVE_2014_3576.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_ACTIVEMQ_CVE_2019_0222 = {
        "name": "apache__activemq_CVE-2019-0222_5.15.8",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_ACTIVEMQ_CVE_2019_0222.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_ACTIVEMQ_CVE_2020_11998 = {
        "name": "apache__activemq_CVE-2020-11998_5.15.12",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_ACTIVEMQ_CVE_2020_11998.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_CAMEL_CVE_2018_8041 = {
        "name": "apache__camel_CVE-2018-8041_2.20.3",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_CAMEL_CVE_2018_8041.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_CAMEL_CVE_2019_0194 = {
        "name": "apache__camel_CVE-2019-0194_2.21.4",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_CAMEL_CVE_2019_0194.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_DOLPHINSCHEDULER_CVE_2022_26884 = {
        "name": "apache__dolphinscheduler_CVE-2022-26884_2.0.5",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_DOLPHINSCHEDULER_CVE_2022_26884.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_DOLPHINSCHEDULER_CVE_2022_34662 = {
        "name": "apache__dolphinscheduler_CVE-2022-34662_2.0.9",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_DOLPHINSCHEDULER_CVE_2022_34662.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_DOLPHINSCHEDULER_CVE_2023_49109 = {
        "name": "apache__dolphinscheduler_CVE-2023-49109_3.2.0",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_DOLPHINSCHEDULER_CVE_2023_49109.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_DOLPHINSCHEDULER_CVE_2023_51770 = {
        "name": "apache__dolphinscheduler_CVE-2023-51770_3.2.0",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_DOLPHINSCHEDULER_CVE_2023_51770.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_DUBBO_CVE_2021_30180 = {
        "name": "apache__dubbo_CVE-2021-30180_2.7.9",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_DUBBO_CVE_2021_30180.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_FLINK_CVE_2020_17519 = {
        "name": "apache__flink_CVE-2020-17519_1.11.2",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_FLINK_CVE_2020_17519.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_INCUBATOR_DUBBO_CVE_2021_30181 = {
        "name": "apache__incubator-dubbo_CVE-2021-30181_2.6.8",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_INCUBATOR_DUBBO_CVE_2021_30181.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_JSPWIKI_CVE_2019_0225 = {
        "name": "apache__jspwiki_CVE-2019-0225_2.11.0.M2",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_JSPWIKI_CVE_2019_0225.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_JSPWIKI_CVE_2019_10076 = {
        "name": "apache__jspwiki_CVE-2019-10076_2.11.0.M3",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_JSPWIKI_CVE_2019_10076.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_JSPWIKI_CVE_2019_10077 = {
        "name": "apache__jspwiki_CVE-2019-10077_2.11.0.M3",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_JSPWIKI_CVE_2019_10077.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_JSPWIKI_CVE_2019_10078 = {
        "name": "apache__jspwiki_CVE-2019-10078_2.11.0.M3",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_JSPWIKI_CVE_2019_10078.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_JSPWIKI_CVE_2019_10089 = {
        "name": "apache__jspwiki_CVE-2019-10089_2.11.0.M4",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_JSPWIKI_CVE_2019_10089.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_JSPWIKI_CVE_2022_46907 = {
        "name": "apache__jspwiki_CVE-2022-46907_2.11.3",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_JSPWIKI_CVE_2022_46907.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_MINA_SSHD_CVE_2023_35887 = {
        "name": "apache__mina-sshd_CVE-2023-35887_2.9.2",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_MINA_SSHD_CVE_2023_35887.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_MYFACES_CVE_2011_4367 = {
        "name": "apache__myfaces_CVE-2011-4367_2.0.11",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_MYFACES_CVE_2011_4367.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_NIFI_CVE_2022_33140 = {
        "name": "apache__nifi_CVE-2022-33140_1.16.2",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_NIFI_CVE_2022_33140.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_ROCKETMQ_CVE_2019_17572 = {
        "name": "apache__rocketmq_CVE-2019-17572_4.6.0",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_ROCKETMQ_CVE_2019_17572.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_ROCKETMQ_CVE_2023_33246 = {
        "name": "apache__rocketmq_CVE-2023-33246_5.1.0",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_ROCKETMQ_CVE_2023_33246.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_ROCKETMQ_CVE_2023_37582 = {
        "name": "apache__rocketmq_CVE-2023-37582_4.9.6",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_ROCKETMQ_CVE_2023_37582.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_SHIRO_CVE_2023_34478 = {
        "name": "apache__shiro_CVE-2023-34478_1.11.0",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_SHIRO_CVE_2023_34478.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_SHIRO_CVE_2023_46749 = {
        "name": "apache__shiro_CVE-2023-46749_1.12.0",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_SHIRO_CVE_2023_46749.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_SLING_ORG_APACHE_SLING_SERVLETS_RESOLVER_CVE_2024_23673 = {
        "name": "apache__sling-org-apache-sling-servlets-resolver_CVE-2024-23673_2.10.0",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_SLING_ORG_APACHE_SLING_SERVLETS_RESOLVER_CVE_2024_23673.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_SLING_ORG_APACHE_SLING_XSS_CVE_2016_5394 = {
        "name": "apache__sling-org-apache-sling-xss_CVE-2016-5394_1.0.8",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_SLING_ORG_APACHE_SLING_XSS_CVE_2016_5394.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_STRUTS_CVE_2020_17530 = {
        "name": "apache__struts_CVE-2020-17530_2.5.25",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_STRUTS_CVE_2020_17530.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_TIKA_CVE_2018_11762 = {
        "name": "apache__tika_CVE-2018-11762_1.18",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_TIKA_CVE_2018_11762.json",
        "dummy_exploiter_pov_logic": "..."
    }

    APACHE_UIMA_UIMAJ_CVE_2022_32287 = {
        "name": "apache__uima-uimaj_CVE-2022-32287_3.3.0",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/APACHE_UIMA_UIMAJ_CVE_2022_32287.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_COMMONS_IO_CVE_2021_29425 = {
        "name": "asf__commons-io_CVE-2021-29425_2.6",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/ASF_COMMONS_IO_CVE_2021_29425.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_COMMONS_TEXT_CVE_2022_42889 = {
        "name": "asf__commons-text_CVE-2022-42889_1.9",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/ASF_COMMONS_TEXT_CVE_2022_42889.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_CXF_CVE_2016_6812 = {
        "name": "asf__cxf_CVE-2016-6812_3.0.11",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/ASF_CXF_CVE_2016_6812.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_CXF_CVE_2019_17573 = {
        "name": "asf__cxf_CVE-2019-17573_3.2.11",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/ASF_CXF_CVE_2019_17573.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_JAMES_PROJECT_CVE_2022_22931 = {
        "name": "asf__james-project_CVE-2022-22931_3.6.0",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/ASF_JAMES_PROJECT_CVE_2022_22931.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_KARAF_CVE_2022_22932 = {
        "name": "asf__karaf_CVE-2022-22932_4.3.5",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/ASF_KARAF_CVE_2022_22932.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_NIFI_CVE_2023_34468 = {
        "name": "asf__nifi_CVE-2023-34468_1.21.0",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/ASF_NIFI_CVE_2023_34468.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_NIFI_CVE_2023_36542 = {
        "name": "asf__nifi_CVE-2023-36542_1.22.0",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/ASF_NIFI_CVE_2023_36542.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ASF_TAPESTRY_5_CVE_2019_0207 = {
        "name": "asf__tapestry-5_CVE-2019-0207_5.4.4",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/ASF_TAPESTRY_5_CVE_2019_0207.json",
        "dummy_exploiter_pov_logic": "..."
    }

    AWS_AWS_SDK_JAVA_CVE_2022_31159 = {
        "name": "aws__aws-sdk-java_CVE-2022-31159_1.12.260",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/AWS_AWS_SDK_JAVA_CVE_2022_31159.json",
        "dummy_exploiter_pov_logic": "..."
    }

    CODECENTRIC_SPRING_BOOT_ADMIN_CVE_2022_46166 = {
        "name": "codecentric__spring-boot-admin_CVE-2022-46166_2.6.9",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/CODECENTRIC_SPRING_BOOT_ADMIN_CVE_2022_46166.json",
        "dummy_exploiter_pov_logic": "..."
    }

    CODEHAUS_PLEXUS_PLEXUS_ARCHIVER_CVE_2018_1002200 = {
        "name": "codehaus-plexus__plexus-archiver_CVE-2018-1002200_3.5",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/CODEHAUS_PLEXUS_PLEXUS_ARCHIVER_CVE_2018_1002200.json",
        "dummy_exploiter_pov_logic": "..."
    }

    CODEHAUS_PLEXUS_PLEXUS_ARCHIVER_CVE_2023_37460 = {
        "name": "codehaus-plexus__plexus-archiver_CVE-2023-37460_4.7.1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/CODEHAUS_PLEXUS_PLEXUS_ARCHIVER_CVE_2023_37460.json",
        "dummy_exploiter_pov_logic": "..."
    }

    CODEHAUS_PLEXUS_PLEXUS_UTILS_CVE_2017_1000487 = {
        "name": "codehaus-plexus__plexus-utils_CVE-2017-1000487_3.0.15",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/CODEHAUS_PLEXUS_PLEXUS_UTILS_CVE_2017_1000487.json",
        "dummy_exploiter_pov_logic": "..."
    }

    CODEHAUS_PLEXUS_PLEXUS_UTILS_CVE_2022_4244 = {
        "name": "codehaus-plexus__plexus-utils_CVE-2022-4244_3.0.23",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/CODEHAUS_PLEXUS_PLEXUS_UTILS_CVE_2022_4244.json",
        "dummy_exploiter_pov_logic": "..."
    }

    DIFFPLUG_GOOMPH_CVE_2022_26049 = {
        "name": "diffplug__goomph_CVE-2022-26049_3.37.1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/DIFFPLUG_GOOMPH_CVE_2022_26049.json",
        "dummy_exploiter_pov_logic": "..."
    }

    DROMARA_HUTOOL_CVE_2018_17297 = {
        "name": "dromara__hutool_CVE-2018-17297_4.1.11",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/DROMARA_HUTOOL_CVE_2018_17297.json",
        "dummy_exploiter_pov_logic": "..."
    }

    DSPACE_DSPACE_CVE_2016_10726 = {
        "name": "DSpace__DSpace_CVE-2016-10726_4.4",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/DSPACE_DSPACE_CVE_2016_10726.json",
        "dummy_exploiter_pov_logic": "..."
    }

    DSPACE_DSPACE_CVE_2022_31192 = {
        "name": "DSpace__DSpace_CVE-2022-31192_5.10",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/DSPACE_DSPACE_CVE_2022_31192.json",
        "dummy_exploiter_pov_logic": "..."
    }

    DSPACE_DSPACE_CVE_2022_31194 = {
        "name": "DSpace__DSpace_CVE-2022-31194_5.10",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/DSPACE_DSPACE_CVE_2022_31194.json",
        "dummy_exploiter_pov_logic": "..."
    }

    DSPACE_DSPACE_CVE_2022_31195 = {
        "name": "DSpace__DSpace_CVE-2022-31195_5.10",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/DSPACE_DSPACE_CVE_2022_31195.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ECLIPSE_HAWKBIT_CVE_2020_27219 = {
        "name": "eclipse__hawkbit_CVE-2020-27219_0.3.0M6",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/ECLIPSE_HAWKBIT_CVE_2020_27219.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ECLIPSE_EE4J_GLASSFISH_CVE_2022_2712 = {
        "name": "eclipse-ee4j__glassfish_CVE-2022-2712_6.2.5",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/ECLIPSE_EE4J_GLASSFISH_CVE_2022_2712.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ESAPI_ESAPI_JAVA_LEGACY_CVE_2022_23457 = {
        "name": "ESAPI__esapi-java-legacy_CVE-2022-23457_2.2.3.1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/ESAPI_ESAPI_JAVA_LEGACY_CVE_2022_23457.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ESAPI_ESAPI_JAVA_LEGACY_CVE_2022_24891 = {
        "name": "ESAPI__esapi-java-legacy_CVE-2022-24891_2.2.3.1",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/ESAPI_ESAPI_JAVA_LEGACY_CVE_2022_24891.json",
        "dummy_exploiter_pov_logic": "..."
    }

    FABRIC8IO_KUBERNETES_CLIENT_CVE_2021_4178 = {
        "name": "fabric8io__kubernetes-client_CVE-2021-4178_5.0.2",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/FABRIC8IO_KUBERNETES_CLIENT_CVE_2021_4178.json",
        "dummy_exploiter_pov_logic": "..."
    }

    FF4J_FF4J_CVE_2022_44262 = {
        "name": "ff4j__ff4j_CVE-2022-44262_1.8.13",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/FF4J_FF4J_CVE_2022_44262.json",
        "dummy_exploiter_pov_logic": "..."
    }

    GRAYLOG2_GRAYLOG2_SERVER_CVE_2023_41044 = {
        "name": "Graylog2__graylog2-server_CVE-2023-41044_5.1.2",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/GRAYLOG2_GRAYLOG2_SERVER_CVE_2023_41044.json",
        "dummy_exploiter_pov_logic": "..."
    }

    HAPIFHIR_ORG_HL7_FHIR_CORE_CVE_2023_24057 = {
        "name": "hapifhir__org.hl7.fhir.core_CVE-2023-24057_5.6.91",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/HAPIFHIR_ORG_HL7_FHIR_CORE_CVE_2023_24057.json",
        "dummy_exploiter_pov_logic": "..."
    }

    HAPIFHIR_ORG_HL7_FHIR_CORE_CVE_2023_28465 = {
        "name": "hapifhir__org.hl7.fhir.core_CVE-2023-28465_5.6.105",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/HAPIFHIR_ORG_HL7_FHIR_CORE_CVE_2023_28465.json",
        "dummy_exploiter_pov_logic": "..."
    }

    HIBERNATE_HIBERNATE_VALIDATOR_CVE_2019_10219 = {
        "name": "hibernate__hibernate-validator_CVE-2019-10219_6.0.17.Final",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/HIBERNATE_HIBERNATE_VALIDATOR_CVE_2019_10219.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JENKINSCI_DOCKER_COMMONS_PLUGIN_CVE_2022_20617 = {
        "name": "jenkinsci__docker-commons-plugin_CVE-2022-20617_1.17",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/JENKINSCI_DOCKER_COMMONS_PLUGIN_CVE_2022_20617.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JENKINSCI_GIT_CLIENT_PLUGIN_CVE_2019_10392 = {
        "name": "jenkinsci__git-client-plugin_CVE-2019-10392_2.8.4",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/JENKINSCI_GIT_CLIENT_PLUGIN_CVE_2019_10392.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JENKINSCI_PERFECTO_PLUGIN_CVE_2020_2261 = {
        "name": "jenkinsci__perfecto-plugin_CVE-2020-2261_1.17",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/JENKINSCI_PERFECTO_PLUGIN_CVE_2020_2261.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JENKINSCI_SCRIPT_SECURITY_PLUGIN_CVE_2023_24422 = {
        "name": "jenkinsci__script-security-plugin_CVE-2023-24422_1228.vd93135a_2fb_25",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/JENKINSCI_SCRIPT_SECURITY_PLUGIN_CVE_2023_24422.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JENKINSCI_WORKFLOW_CPS_GLOBAL_LIB_PLUGIN_CVE_2022_25174 = {
        "name": "jenkinsci__workflow-cps-global-lib-plugin_CVE-2022-25174_544.vff04fa68714d",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/JENKINSCI_WORKFLOW_CPS_GLOBAL_LIB_PLUGIN_CVE_2022_25174.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JENKINSCI_WORKFLOW_CPS_PLUGIN_CVE_2022_25173 = {
        "name": "jenkinsci__workflow-cps-plugin_CVE-2022-25173_2646.v6ed3b5b01ff1",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/JENKINSCI_WORKFLOW_CPS_PLUGIN_CVE_2022_25173.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JENKINSCI_WORKFLOW_MULTIBRANCH_PLUGIN_CVE_2022_25175 = {
        "name": "jenkinsci__workflow-multibranch-plugin_CVE-2022-25175_706.vd43c65dec013",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/JENKINSCI_WORKFLOW_MULTIBRANCH_PLUGIN_CVE_2022_25175.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JEREMYLONG_DEPENDENCYCHECK_CVE_2018_12036 = {
        "name": "jeremylong__DependencyCheck_CVE-2018-12036_3.1.2",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/JEREMYLONG_DEPENDENCYCHECK_CVE_2018_12036.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JLANGCH_VENICE_CVE_2022_36007 = {
        "name": "jlangch__venice_CVE-2022-36007_1.10.16",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/JLANGCH_VENICE_CVE_2022_36007.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JMROZANEC_CRON_UTILS_CVE_2021_41269 = {
        "name": "jmrozanec__cron-utils_CVE-2021-41269_9.1.5",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/JMROZANEC_CRON_UTILS_CVE_2021_41269.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JONILES_MPXJ_CVE_2020_35460 = {
        "name": "joniles__mpxj_CVE-2020-35460_8.3.4",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/JONILES_MPXJ_CVE_2020_35460.json",
        "dummy_exploiter_pov_logic": "..."
    }

    JSTACHIO_JSTACHIO_CVE_2023_33962 = {
        "name": "jstachio__jstachio_CVE-2023-33962_1.0.0",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/JSTACHIO_JSTACHIO_CVE_2023_33962.json",
        "dummy_exploiter_pov_logic": "..."
    }

    KEYCLOAK_KEYCLOAK_CVE_2014_3656 = {
        "name": "keycloak__keycloak_CVE-2014-3656_1.0.5.Final",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/KEYCLOAK_KEYCLOAK_CVE_2014_3656.json",
        "dummy_exploiter_pov_logic": "..."
    }

    KEYCLOAK_KEYCLOAK_CVE_2022_1274 = {
        "name": "keycloak__keycloak_CVE-2022-1274_20.0.4",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/KEYCLOAK_KEYCLOAK_CVE_2022_1274.json",
        "dummy_exploiter_pov_logic": "..."
    }

    KEYCLOAK_KEYCLOAK_CVE_2022_3782 = {
        "name": "keycloak__keycloak_CVE-2022-3782_20.0.1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/KEYCLOAK_KEYCLOAK_CVE_2022_3782.json",
        "dummy_exploiter_pov_logic": "..."
    }

    KEYCLOAK_KEYCLOAK_CVE_2022_4137 = {
        "name": "keycloak__keycloak_CVE-2022-4137_20.0.4",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/KEYCLOAK_KEYCLOAK_CVE_2022_4137.json",
        "dummy_exploiter_pov_logic": "..."
    }

    KEYCLOAK_KEYCLOAK_CVE_2022_4361 = {
        "name": "keycloak__keycloak_CVE-2022-4361_21.1.1",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/KEYCLOAK_KEYCLOAK_CVE_2022_4361.json",
        "dummy_exploiter_pov_logic": "..."
    }

    KUBERNETES_CLIENT_JAVA_CVE_2020_8570 = {
        "name": "kubernetes-client__java_CVE-2020-8570_client-java-parent-9.0.1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/KUBERNETES_CLIENT_JAVA_CVE_2020_8570.json",
        "dummy_exploiter_pov_logic": "..."
    }

    NAHSRA_ANTISAMY_CVE_2016_10006 = {
        "name": "nahsra__antisamy_CVE-2016-10006_1.5.3",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/NAHSRA_ANTISAMY_CVE_2016_10006.json",
        "dummy_exploiter_pov_logic": "..."
    }

    NAHSRA_ANTISAMY_CVE_2017_14735 = {
        "name": "nahsra__antisamy_CVE-2017-14735_1.5.6",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/NAHSRA_ANTISAMY_CVE_2017_14735.json",
        "dummy_exploiter_pov_logic": "..."
    }

    NAHSRA_ANTISAMY_CVE_2022_28367 = {
        "name": "nahsra__antisamy_CVE-2022-28367_1.6.5",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/NAHSRA_ANTISAMY_CVE_2022_28367.json",
        "dummy_exploiter_pov_logic": "..."
    }

    NAHSRA_ANTISAMY_CVE_2022_29577 = {
        "name": "nahsra__antisamy_CVE-2022-29577_1.6.6.1",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/NAHSRA_ANTISAMY_CVE_2022_29577.json",
        "dummy_exploiter_pov_logic": "..."
    }

    OWASP_JSON_SANITIZER_CVE_2020_13973 = {
        "name": "OWASP__json-sanitizer_CVE-2020-13973_1.2.0",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/OWASP_JSON_SANITIZER_CVE_2020_13973.json",
        "dummy_exploiter_pov_logic": "..."
    }

    PAYARA_PAYARA_CVE_2022_37422 = {
        "name": "payara__Payara_CVE-2022-37422_5.2022.2",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/PAYARA_PAYARA_CVE_2022_37422.json",
        "dummy_exploiter_pov_logic": "..."
    }

    PERWENDEL_SPARK_CVE_2016_9177 = {
        "name": "perwendel__spark_CVE-2016-9177_2.5.1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/PERWENDEL_SPARK_CVE_2016_9177.json",
        "dummy_exploiter_pov_logic": "..."
    }

    PERWENDEL_SPARK_CVE_2018_9159 = {
        "name": "perwendel__spark_CVE-2018-9159_2.7.1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/PERWENDEL_SPARK_CVE_2018_9159.json",
        "dummy_exploiter_pov_logic": "..."
    }

    RHUSS_JOLOKIA_CVE_2018_1000129 = {
        "name": "rhuss__jolokia_CVE-2018-1000129_1.4.0",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/RHUSS_JOLOKIA_CVE_2018_1000129.json",
        "dummy_exploiter_pov_logic": "..."
    }

    SPRING_CLOUD_SPRING_CLOUD_CONFIG_CVE_2020_5405 = {
        "name": "spring-cloud__spring-cloud-config_CVE-2020-5405_2.1.6.RELEASE",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/SPRING_CLOUD_SPRING_CLOUD_CONFIG_CVE_2020_5405.json",
        "dummy_exploiter_pov_logic": "..."
    }

    SPRING_CLOUD_SPRING_CLOUD_CONFIG_CVE_2020_5410 = {
        "name": "spring-cloud__spring-cloud-config_CVE-2020-5410_2.1.8.RELEASE",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/SPRING_CLOUD_SPRING_CLOUD_CONFIG_CVE_2020_5410.json",
        "dummy_exploiter_pov_logic": "..."
    }

    SPRING_CLOUD_SPRING_CLOUD_GATEWAY_CVE_2022_22947 = {
        "name": "spring-cloud__spring-cloud-gateway_CVE-2022-22947_3.0.6",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/SPRING_CLOUD_SPRING_CLOUD_GATEWAY_CVE_2022_22947.json",
        "dummy_exploiter_pov_logic": "..."
    }

    SPRING_PROJECTS_SPRING_FRAMEWORK_CVE_2022_22965 = {
        "name": "spring-projects__spring-framework_CVE-2022-22965_5.2.19.RELEASE",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/SPRING_PROJECTS_SPRING_FRAMEWORK_CVE_2022_22965.json",
        "dummy_exploiter_pov_logic": "..."
    }

    SPRING_PROJECTS_SPRING_SECURITY_CVE_2011_2732 = {
        "name": "spring-projects__spring-security_CVE-2011-2732_2.0.6.RELEASE",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/SPRING_PROJECTS_SPRING_SECURITY_CVE_2011_2732.json",
        "dummy_exploiter_pov_logic": "..."
    }

    SPRINGSOURCE_SPRING_SECURITY_OAUTH_CVE_2018_1260 = {
        "name": "SpringSource__spring-security-oauth_CVE-2018-1260_2.3.2.RELEASE",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/SPRINGSOURCE_SPRING_SECURITY_OAUTH_CVE_2018_1260.json",
        "dummy_exploiter_pov_logic": "..."
    }

    SQUARE_RETROFIT_CVE_2018_1000850 = {
        "name": "square__retrofit_CVE-2018-1000850_2.4.0",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/SQUARE_RETROFIT_CVE_2018_1000850.json",
        "dummy_exploiter_pov_logic": "..."
    }

    SRIKANTH_LINGALA_ZIP4J_CVE_2018_1002202 = {
        "name": "srikanth-lingala__zip4j_CVE-2018-1002202_1.3.2",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/SRIKANTH_LINGALA_ZIP4J_CVE_2018_1002202.json",
        "dummy_exploiter_pov_logic": "..."
    }

    TESTNG_TEAM_TESTNG_CVE_2022_4065 = {
        "name": "testng-team__testng_CVE-2022-4065_7.5",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/TESTNG_TEAM_TESTNG_CVE_2022_4065.json",
        "dummy_exploiter_pov_logic": "..."
    }

    UNDERTOW_IO_UNDERTOW_CVE_2014_7816 = {
        "name": "undertow-io__undertow_CVE-2014-7816_1.0.16.Final",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/UNDERTOW_IO_UNDERTOW_CVE_2014_7816.json",
        "dummy_exploiter_pov_logic": "..."
    }

    VERT_X3_VERTX_WEB_CVE_2018_12542 = {
        "name": "vert-x3__vertx-web_CVE-2018-12542_3.5.3.CR1",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/VERT_X3_VERTX_WEB_CVE_2018_12542.json",
        "dummy_exploiter_pov_logic": "..."
    }

    VERT_X3_VERTX_WEB_CVE_2019_17640 = {
        "name": "vert-x3__vertx-web_CVE-2019-17640_3.9.3",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/VERT_X3_VERTX_WEB_CVE_2019_17640.json",
        "dummy_exploiter_pov_logic": "..."
    }

    WHITESOURCE_CUREKIT_CVE_2022_23082 = {
        "name": "whitesource__curekit_CVE-2022-23082_1.1.3",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/WHITESOURCE_CUREKIT_CVE_2022_23082.json",
        "dummy_exploiter_pov_logic": "..."
    }

    WILDFLY_WILDFLY_CVE_2018_1047 = {
        "name": "wildfly__wildfly_CVE-2018-1047_11.0.0.Final",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/WILDFLY_WILDFLY_CVE_2018_1047.json",
        "dummy_exploiter_pov_logic": "..."
    }

    X_STREAM_XSTREAM_CVE_2013_7285 = {
        "name": "x-stream__xstream_CVE-2013-7285_1.4.6",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/X_STREAM_XSTREAM_CVE_2013_7285.json",
        "dummy_exploiter_pov_logic": "..."
    }

    X_STREAM_XSTREAM_CVE_2020_26217 = {
        "name": "x-stream__xstream_CVE-2020-26217_1.4.14-java7",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/X_STREAM_XSTREAM_CVE_2020_26217.json",
        "dummy_exploiter_pov_logic": "..."
    }

    X_STREAM_XSTREAM_CVE_2021_21345 = {
        "name": "x-stream__xstream_CVE-2021-21345_1.4.15",
        "cwe_id": "cwe-078",
        "dummy_finder_output": "Projects/Finder_Output/X_STREAM_XSTREAM_CVE_2021_21345.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XERIAL_SQLITE_JDBC_CVE_2023_32697 = {
        "name": "xerial__sqlite-jdbc_CVE-2023-32697_3.41.2.1",
        "cwe_id": "cwe-094",
        "dummy_finder_output": "Projects/Finder_Output/XERIAL_SQLITE_JDBC_CVE_2023_32697.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XUXUELI_XXL_JOB_CVE_2020_29204 = {
        "name": "xuxueli__xxl-job_CVE-2020-29204_2.2.0",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/XUXUELI_XXL_JOB_CVE_2020_29204.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XWIKI_XWIKI_COMMONS_CVE_2022_24897 = {
        "name": "xwiki__xwiki-commons_CVE-2022-24897_12.6.6",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/XWIKI_XWIKI_COMMONS_CVE_2022_24897.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XWIKI_XWIKI_COMMONS_CVE_2023_29201 = {
        "name": "xwiki__xwiki-commons_CVE-2023-29201_14.6",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/XWIKI_XWIKI_COMMONS_CVE_2023_29201.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XWIKI_XWIKI_COMMONS_CVE_2023_29528 = {
        "name": "xwiki__xwiki-commons_CVE-2023-29528_14.9-rc-1",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/XWIKI_XWIKI_COMMONS_CVE_2023_29528.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XWIKI_XWIKI_COMMONS_CVE_2023_31126 = {
        "name": "xwiki__xwiki-commons_CVE-2023-31126_14.10.3",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/XWIKI_XWIKI_COMMONS_CVE_2023_31126.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XWIKI_XWIKI_COMMONS_CVE_2023_36471 = {
        "name": "xwiki__xwiki-commons_CVE-2023-36471_14.10.5",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/XWIKI_XWIKI_COMMONS_CVE_2023_36471.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XWIKI_XWIKI_RENDERING_CVE_2023_32070 = {
        "name": "xwiki__xwiki-rendering_CVE-2023-32070_14.6",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/XWIKI_XWIKI_RENDERING_CVE_2023_32070.json",
        "dummy_exploiter_pov_logic": "..."
    }

    XWIKI_XWIKI_RENDERING_CVE_2023_37908 = {
        "name": "xwiki__xwiki-rendering_CVE-2023-37908_14.10.3",
        "cwe_id": "cwe-079",
        "dummy_finder_output": "Projects/Finder_Output/XWIKI_XWIKI_RENDERING_CVE_2023_37908.json",
        "dummy_exploiter_pov_logic": "..."
    }

    YAMCS_YAMCS_CVE_2023_45277 = {
        "name": "yamcs__yamcs_CVE-2023-45277_5.8.6",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/YAMCS_YAMCS_CVE_2023_45277.json",
        "dummy_exploiter_pov_logic": "..."
    }

    YAMCS_YAMCS_CVE_2023_45278 = {
        "name": "yamcs__yamcs_CVE-2023-45278_5.8.6",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/YAMCS_YAMCS_CVE_2023_45278.json",
        "dummy_exploiter_pov_logic": "..."
    }

    ZEROTURNAROUND_ZT_ZIP_CVE_2018_1002201 = {
        "name": "zeroturnaround__zt-zip_CVE-2018-1002201_1.12",
        "cwe_id": "cwe-022",
        "dummy_finder_output": "Projects/Finder_Output/ZEROTURNAROUND_ZT_ZIP_CVE_2018_1002201.json",
        "dummy_exploiter_pov_logic": "..."
    }

    @property
    def project_name(self) -> str:
        return self.value["name"]

    @property
    def cwe_id(self) -> str:
        return self.value["cwe_id"]

    @property
    def dummy_finder_output(self) -> str:
        return self.value["dummy_finder_output"]

    @property
    def dummy_exploiter_pov_logic(self) -> str | None:
        return self.value.get("dummy_exploiter_pov_logic")

    @classmethod
    def from_project_slug(cls, project_slug: str) -> "ProjectVariants":
        for variant in cls:
            if variant.project_name == project_slug:
                return variant

        raise ValueError(f"No ProjectVariants entry found for project slug: {project_slug}")

    @classmethod
    def by_cwe(cls, cwe_id: str) -> list["ProjectVariants"]:
        normalized_cwe_id = cwe_id.lower()
        return [variant for variant in cls if variant.cwe_id == normalized_cwe_id]

    @classmethod
    def valid_for_experiment(cls) -> list["ProjectVariants"]:
        return [
            variant
            for variant in cls
            if variant.cwe_id != "cwe-noinfo"
        ]
